FROM node:22-alpine AS build

WORKDIR /app

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_LOCAL_ADMIN_PASSWORD
ARG VITE_VM_SYNC_ENDPOINT
ARG VITE_INLINE_EMPLOYEE_PHOTOS=true

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_LOCAL_ADMIN_PASSWORD=$VITE_LOCAL_ADMIN_PASSWORD
ENV VITE_VM_SYNC_ENDPOINT=$VITE_VM_SYNC_ENDPOINT
ENV VITE_INLINE_EMPLOYEE_PHOTOS=$VITE_INLINE_EMPLOYEE_PHOTOS

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

COPY deploy/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
